In [275]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import random
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix

In [276]:
review_raw = pd.read_csv('yelp_labelled.txt', delimiter= '\t', header=None)

review_raw.columns = ['message', 'sentement']

review_raw.head()

message  sentement
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [277]:
keywords = [ 'only', 'back', 'very', 'over', 'food', 'took', 'horrible', 'don\'t', 'least', 'much', 'excuse', 'down', 'bad', 'any', 'sucks', 'final', 'worst', 'hate', 'hated', 'never','not', 'slow', 'nasty', 'angry', 'didn\'t', 'poor', 'no']

In [278]:
for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    review_raw[str(key)] = review_raw.message.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )
    
review_raw['allcaps'] = review_raw.message.str.isupper()

data = review_raw[keywords + ['allcaps']]
target = review_raw['sentement']

# Our data is binary / boolean, so we're importing the Bernoulli classifier.
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

# Display our results.
print("Number of mislabeled points out of a total {} points : {} \n".format(data.shape[0], (target != y_pred).sum()))

print('Precent accuracy: {} \n'.format(100*(1000-322)/1000))
confusion_matrix(target, y_pred)

Number of mislabeled points out of a total 1000 points : 322 

Precent accuracy: 67.8 



array([[215, 285],
       [ 37, 463]], dtype=int64)

In [279]:
print(cross_val_score(bnb, data, target, cv=10))
for i in range(0 , 10):
    datahold = data.sample(n=100, replace=False)
    indexval = datahold.index.values.tolist()
    targethold = target.take(indexval)
    
    X_train, X_test, y_train, y_test = train_test_split(datahold, targethold, test_size=0.2, random_state=20)
    
    y_pred = bnb.fit(datahold, targethold).predict(datahold)
    
    k = confusion_matrix(targethold, y_pred)
    
    print('With 20% Holdout: ' + str(100*bnb.fit(X_train, y_train).score(X_test, y_test)))
    #print('Testing sample: ' + str(100*bnb.fit(X_train, y_train).score(X_train, y_train)))
    print(k)
    print('percentage of true positive: ' + str(100*k[0][0]/(k[0][0] + k[0][1])))
    print('percentage of true negative: ' + str(100*k[1][1]/(k[1][0] + k[1][1])) + '\n')

[ 0.72  0.62  0.72  0.59  0.67  0.64  0.69  0.66  0.62  0.66]
With 20% Holdout: 65.0
[[56  3]
 [34  7]]
percentage of true positive: 94.9152542373
percentage of true negative: 17.0731707317

With 20% Holdout: 80.0
[[16 25]
 [ 2 57]]
percentage of true positive: 39.0243902439
percentage of true negative: 96.6101694915

With 20% Holdout: 65.0
[[17 31]
 [ 1 51]]
percentage of true positive: 35.4166666667
percentage of true negative: 98.0769230769

With 20% Holdout: 75.0
[[22 29]
 [ 5 44]]
percentage of true positive: 43.137254902
percentage of true negative: 89.7959183673

With 20% Holdout: 65.0
[[20 32]
 [ 2 46]]
percentage of true positive: 38.4615384615
percentage of true negative: 95.8333333333

With 20% Holdout: 65.0
[[15 28]
 [ 3 54]]
percentage of true positive: 34.8837209302
percentage of true negative: 94.7368421053

With 20% Holdout: 70.0
[[27 28]
 [ 2 43]]
percentage of true positive: 49.0909090909
percentage of true negative: 95.5555555556

With 20% Holdout: 40.0
[[21 32]
 [ 6

In [280]:
review_raw = pd.read_csv('yelp_labelled.txt', delimiter= '\t', header=None)

review_raw.columns = ['message', 'sentement']

review_raw.head()

message  sentement
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

Above is evaluation of my first classifier model. The performance based on accuracy. There overfitting due to the difference in perforance of training and test data sets and the inconsistancy between the folds. Lot of the error is due to false positive, our feature set is more email as spam than ham. Although we are perdicting hams at very high percentage, we are letting in alot of spams, so I should focus more on feature engeneering to correctly perdict spams. 

In [281]:
#keywords = [ 'only', 'back', 'very', 'over', 'food', 'took', 'horrible', 'don\'t', 'least', 'much', 'excuse', 'down', 'bad', 'any', 'sucks', 'final', 'worst', 'hate', 'hated', 'never','not', 'slow', 'nasty', 'angry', 'didn\'t', 'poor', 'no']
keywords2 = [ 'only', 'very', 'over', 'don\'t', 'least', 'took', 'much', 'down', 'bad', 'any', 'hate', 'hated', 'never','not', 'didn\'t', 'no']

In [282]:
for key in keywords2:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    review_raw[str(key)] = review_raw.message.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data2 = review_raw[keywords2]
target = review_raw['sentement']

print(cross_val_score(bnb, data2, target2, cv=10))

for i in range(0 , 10):
    datahold = data2.sample(n=100, replace=False)
    indexval = datahold.index.values.tolist()
    targethold = target2.take(indexval)
    
    X_train, X_test, y_train, y_test = train_test_split(datahold, targethold, test_size=0.2, random_state=20)
    
    y_pred = bnb.fit(datahold, targethold).predict(datahold)
    
    k = confusion_matrix(targethold, y_pred)
    
    print('With 20% Holdout: ' + str(100*bnb.fit(X_train, y_train).score(X_test, y_test)))
    #print('Testing sample: ' + str(100*bnb.fit(X_train, y_train).score(X_train, y_train)))
    print(k)
    print('percentage of true positive: ' + str(100*k[0][0]/(k[0][0] + k[0][1])))
    print('percentage of true negative: ' + str(100*k[1][1]/(k[1][0] + k[1][1])) + '\n')

[ 0.52  0.56  0.45  0.54  0.51  0.49  0.49  0.53  0.48  0.51]
With 20% Holdout: 50.0
[[16 37]
 [ 5 42]]
percentage of true positive: 30.1886792453
percentage of true negative: 89.3617021277

With 20% Holdout: 40.0
[[13 36]
 [ 3 48]]
percentage of true positive: 26.5306122449
percentage of true negative: 94.1176470588

With 20% Holdout: 40.0
[[56  2]
 [37  5]]
percentage of true positive: 96.5517241379
percentage of true negative: 11.9047619048

With 20% Holdout: 30.0
[[17 34]
 [ 6 43]]
percentage of true positive: 33.3333333333
percentage of true negative: 87.7551020408

With 20% Holdout: 40.0
[[49  2]
 [42  7]]
percentage of true positive: 96.0784313725
percentage of true negative: 14.2857142857

With 20% Holdout: 30.0
[[49  3]
 [38 10]]
percentage of true positive: 94.2307692308
percentage of true negative: 20.8333333333

With 20% Holdout: 45.0
[[14 34]
 [ 7 45]]
percentage of true positive: 29.1666666667
percentage of true negative: 86.5384615385

With 20% Holdout: 50.0
[[11 38]
 [ 

For the second feature set I removed all the words that are not adverb. The result did not improve, overfitting is lager and the type of error contributing to over all error is random between the folds. The type of error being random might be due to imbalance is the samples for the folds. 

In [283]:
review_raw = pd.read_csv('yelp_labelled.txt', delimiter= '\t', header=None)

review_raw.columns = ['message', 'sentement']

review_raw.head()

message  sentement
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [413]:
k = review_raw[review_raw.sentement == 0].reset_index().drop('index', axis=1)
negFeatureslist = []

for i in k['message']:
    c = i.split(' ')
    for x in c:
        negFeatureslist.append(x)

#negFeatureslist = list(negFeatureslist)
negFeatureslist = ','.join([i for i in negFeatureslist if i.isalpha()])
negFeatureslist = negFeatureslist.split(',')

In [364]:
for key in negFeatureslist:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    review_raw[str(key)] = review_raw.message.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data3 = review_raw[negFeatureslist]
target = review_raw['sentement']

print(cross_val_score(bnb, data2, target2, cv=10))

for i in range(0 , 10):
    datahold = data2.sample(n=100, replace=False)
    indexval = datahold.index.values.tolist()
    targethold = target2.take(indexval)
    
    X_train, X_test, y_train, y_test = train_test_split(datahold, targethold, test_size=0.2, random_state=20)
    
    y_pred = bnb.fit(datahold, targethold).predict(datahold)
    
    k = confusion_matrix(targethold, y_pred)
    
    print('With 20% Holdout: ' + str(100*bnb.fit(X_train, y_train).score(X_test, y_test)))
    #print('Testing sample: ' + str(100*bnb.fit(X_train, y_train).score(X_train, y_train)))
    print(k)
    print('percentage of true positive: ' + str(100*k[0][0]/(k[0][0] + k[0][1])))
    print('percentage of true negative: ' + str(100*k[1][1]/(k[1][0] + k[1][1])) + '\n')

[ 0.52  0.56  0.45  0.54  0.51  0.49  0.49  0.53  0.48  0.51]
With 20% Holdout: 30.0
[[49  3]
 [38 10]]
percentage of true positive: 94.2307692308
percentage of true negative: 20.8333333333

With 20% Holdout: 75.0
[[21 26]
 [ 1 52]]
percentage of true positive: 44.6808510638
percentage of true negative: 98.1132075472

With 20% Holdout: 65.0
[[13 33]
 [ 1 53]]
percentage of true positive: 28.2608695652
percentage of true negative: 98.1481481481

With 20% Holdout: 50.0
[[48  1]
 [44  7]]
percentage of true positive: 97.9591836735
percentage of true negative: 13.7254901961

With 20% Holdout: 40.0
[[51  0]
 [43  6]]
percentage of true positive: 100.0
percentage of true negative: 12.2448979592

With 20% Holdout: 40.0
[[13 39]
 [ 2 46]]
percentage of true positive: 25.0
percentage of true negative: 95.8333333333

With 20% Holdout: 50.0
[[15 35]
 [ 4 46]]
percentage of true positive: 30.0
percentage of true negative: 92.0

With 20% Holdout: 70.0
[[54  3]
 [37  6]]
percentage of true positive:

In [416]:
review_raw = pd.read_csv('yelp_labelled.txt', delimiter= '\t', header=None)

review_raw.columns = ['message', 'sentement']

review_raw.head()


message  sentement
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [414]:
L = review_raw[review_raw.sentement == 1].reset_index().drop('index', axis=1)
posFeatureslist = []
for i in L['message']:
    c = i.split(' ')
    for x in c:
        posFeatureslist.append(x)
posFeatureslist = ','.join([i for i in posFeatureslist if i.isalpha()])
posFeatureslist = posFeatureslist.split(',')

In [366]:

for key in posFeatureslist:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    review_raw[str(key)] = review_raw.message.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data3 = review_raw[posFeatureslist]
target = review_raw['sentement']

print(cross_val_score(bnb, data2, target2, cv=10))

for i in range(0 , 10):
    datahold = data2.sample(n=100, replace=False)
    indexval = datahold.index.values.tolist()
    targethold = target2.take(indexval)
    
    X_train, X_test, y_train, y_test = train_test_split(datahold, targethold, test_size=0.2, random_state=20)
    
    y_pred = bnb.fit(datahold, targethold).predict(datahold)
    
    k = confusion_matrix(targethold, y_pred)
    
    print('With 20% Holdout: ' + str(100*bnb.fit(X_train, y_train).score(X_test, y_test)))
    #print('Testing sample: ' + str(100*bnb.fit(X_train, y_train).score(X_train, y_train)))
    print(k)
    print('percentage of true positive: ' + str(100*k[0][0]/(k[0][0] + k[0][1])))
    print('percentage of true negative: ' + str(100*k[1][1]/(k[1][0] + k[1][1])) + '\n')


[ 0.52  0.56  0.45  0.54  0.51  0.49  0.49  0.53  0.48  0.51]
With 20% Holdout: 50.0
[[50  3]
 [42  5]]
percentage of true positive: 94.3396226415
percentage of true negative: 10.6382978723

With 20% Holdout: 45.0
[[47  6]
 [36 11]]
percentage of true positive: 88.679245283
percentage of true negative: 23.4042553191

With 20% Holdout: 55.0
[[23 29]
 [ 5 43]]
percentage of true positive: 44.2307692308
percentage of true negative: 89.5833333333

With 20% Holdout: 45.0
[[17 35]
 [ 6 42]]
percentage of true positive: 32.6923076923
percentage of true negative: 87.5

With 20% Holdout: 45.0
[[53  3]
 [35  9]]
percentage of true positive: 94.6428571429
percentage of true negative: 20.4545454545

With 20% Holdout: 45.0
[[57  3]
 [35  5]]
percentage of true positive: 95.0
percentage of true negative: 12.5

With 20% Holdout: 40.0
[[ 3 45]
 [ 0 52]]
percentage of true positive: 6.25
percentage of true negative: 100.0

With 20% Holdout: 50.0
[[ 7 34]
 [ 1 58]]
percentage of true positive: 17.073170

In [415]:
samewordlist = []
diffwordlist = []
for i in negFeatureslist:
    for x in posFeatureslist:
        if i == x:
            samewordlist.append(i)
            break

new_list = [key for key in negFeatureslist if key not in samewordlist]

In [417]:

for key in new_list:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    review_raw[str(key)] = review_raw.message.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data3 = review_raw[new_list]
target = review_raw['sentement']

print(cross_val_score(bnb, data2, target2, cv=10))

for i in range(0 , 10):
    datahold = data2.sample(n=100, replace=False)
    indexval = datahold.index.values.tolist()
    targethold = target2.take(indexval)
    
    X_train, X_test, y_train, y_test = train_test_split(datahold, targethold, test_size=0.2, random_state=20)
    
    y_pred = bnb.fit(datahold, targethold).predict(datahold)
    
    k = confusion_matrix(targethold, y_pred)
    
    print('With 20% Holdout: ' + str(100*bnb.fit(X_train, y_train).score(X_test, y_test)))
    #print('Testing sample: ' + str(100*bnb.fit(X_train, y_train).score(X_train, y_train)))
    print(k)
    print('percentage of true positive: ' + str(100*k[0][0]/(k[0][0] + k[0][1])))
    print('percentage of true negative: ' + str(100*k[1][1]/(k[1][0] + k[1][1])) + '\n')

[ 0.52  0.56  0.45  0.54  0.51  0.49  0.49  0.53  0.48  0.51]
With 20% Holdout: 60.0
[[11 39]
 [ 3 47]]
percentage of true positive: 22.0
percentage of true negative: 94.0

With 20% Holdout: 45.0
[[21 34]
 [ 7 38]]
percentage of true positive: 38.1818181818
percentage of true negative: 84.4444444444

With 20% Holdout: 40.0
[[47  2]
 [40 11]]
percentage of true positive: 95.9183673469
percentage of true negative: 21.568627451

With 20% Holdout: 30.0
[[11 39]
 [ 4 46]]
percentage of true positive: 22.0
percentage of true negative: 92.0

With 20% Holdout: 45.0
[[ 8 37]
 [ 2 53]]
percentage of true positive: 17.7777777778
percentage of true negative: 96.3636363636

With 20% Holdout: 45.0
[[14 30]
 [ 7 49]]
percentage of true positive: 31.8181818182
percentage of true negative: 87.5

With 20% Holdout: 55.0
[[ 5 39]
 [ 2 54]]
percentage of true positive: 11.3636363636
percentage of true negative: 96.4285714286

With 20% Holdout: 55.0
[[55  0]
 [42  3]]
percentage of true positive: 100.0
perc

In [420]:
new_list

['Crust',
 'angry',
 'damn',
 'Honeslty',
 'THAT',
 'rubber',
 'ahead',
 'under',
 'ended',
 'wayyy',
 'disgusted',
 'human',
 'shocked',
 'signs',
 'indicate',
 'cash',
 'slow',
 'let',
 'alone',
 'Burrittos',
 'asked',
 'Took',
 'hour',
 'tables',
 'Luke',
 'sever',
 'totally',
 'final',
 'seems',
 'grab',
 'bite',
 'familiar',
 'pub',
 'yourself',
 'favor',
 'look',
 'Poor',
 'stupid',
 'drag',
 'into',
 'establishment',
 'Hard',
 'judge',
 'whether',
 'these',
 'grossed',
 'melted',
 'styrofoam',
 'fear',
 'Frozen',
 'pucks',
 'behind',
 'bad',
 'damn',
 'horrible',
 'attitudes',
 'towards',
 'talk',
 'customers',
 'Heart',
 'Attack',
 'Grill',
 'excuse',
 'strings',
 'ripped',
 'banana',
 'petrified',
 'refill',
 'water',
 'struggle',
 'wave',
 'apparently',
 'salt',
 'batter',
 'took',
 'min',
 'chocolate',
 'guess',
 'should',
 'known',
 'use',
 'common',
 'scallop',
 'appalling',
 'value',
 'Bad',
 'Customer',
 'cheated',
 'wasting',
 'Rice',
 'Coming',
 'experiencing',
 'under